name: application
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dependency:
    path: ../dependency/
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6

dependency_overrides:
  conduit_isolate_exec:
    path: ../../isolate_exec  
