name: conduit_common
version: 3.1.1
description: Common classes shared by conduit projects.
repository: https://github.com/bsutton/conduit-orm

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  conduit_open_api: ^3.1.1

dev_dependencies: 
  lint: ^1.10.0
  
dependency_overrides: 
  conduit_codable: 
    path: ../codable
  conduit_open_api: 
    path: ../open_api
