name: conduit
version: 3.1.2
homepage: https://github.com/conduit-dart/conduit
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.1
  analyzer: ^5.1.0
  collection: ^1.17.0
  conduit_common: ^3.1.1
  conduit_config: ^3.1.1
  conduit_isolate_exec: ^3.1.1
  conduit_open_api: ^3.1.1
  conduit_password_hash: ^3.1.1
  conduit_runtime: ^3.1.1
  crypto: ^3.0.2
  logging: ^1.1.0
  meta: ^1.8.0
  path: ^1.8.2
  package_config: ^2.1.0
  postgres: ^2.5.2
  pub_cache: ^0.3.1
  pub_semver: ^2.1.2
  yaml: ^3.1.1

dev_dependencies:
  http: ^0.13.5
  matcher: ">=0.12.12"
  mockito: ^5.3.2
  pedantic: ^1.11.1
  settings_yaml: ^4.0.0
  test: ^1.21.6
  fs_test_agent:
    path: ../fs_test_agent
  conduit_common_test:
    path: ../common_test
  conduit_test:
    path: ../test_harness

dependency_overrides:
  conduit_codable:
    path: ../codable
  conduit_common:
    path: ../common
  conduit_config:
    path: ../config
  conduit_isolate_exec:
    path: ../isolate_exec
  conduit_open_api:
    path: ../open_api
  conduit_password_hash:
    path: ../password_hash
  conduit_runtime:
    path: ../runtime
  conduit_test:
    path: ../test_harness

executables:
  conduit: conduit
