name: conduit_runtime
version: 3.1.1
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
repository: https://github.com/conduit-dart/conduit-runtime

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  analyzer: ^5.1.0
  args: ^2.3.1
  conduit_isolate_exec: ^3.1.1
  path: ^1.8.2
  package_config: ^2.1.0
  pubspec: ^2.3.0
  yaml: ^3.1.1

dev_dependencies: 
  lint: ^1.10.0
  test: ^1.21.6
  fs_test_agent: 
    path: ../fs_test_agent
    
dependency_overrides: 
  conduit_isolate_exec: 
    path: ../isolate_exec
