name: fs_test_agent
version: 3.1.1
homepage: https://stablekernel.com
description: Utilities for writing tests to validate file system and Dart project directory operations.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  path: ^1.8.2
  pubspec: ^2.3.0
  
dev_dependencies: 
  lint: ^1.10.0
  test: ^1.21.6
