name: conduit_config
version: 3.1.1
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/conduit-dart/conduit-config.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  conduit_runtime: ^3.1.1
  meta: ^1.8.0
  yaml: ^3.1.1
  
dev_dependencies: 
  lint: ^1.10.0
  test: ^1.21.6

dependency_overrides: 
  conduit_isolate_exec: 
    path: ../isolate_exec
  conduit_runtime: 
    path: ../runtime
