name: conduit_open_api
version: 3.1.1
homepage: https://github.com/conduit-dart/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  conduit_codable: ^3.1.1
  meta: ^1.8.0

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.6

dependency_overrides: 
  conduit_codable: 
    path: ../codable
